BASE_TASK_CONFIG_PATH: "configs/audionav/av_nav/replica/audiogoal.yaml"
NUM_PROCESSES: 1
SENSORS: []
TEST_EPISODE_COUNT: 1000
VIDEO_OPTION: []
VISUALIZATION_OPTION: []

EVAL:
  SPLIT: "test_telephone"
  USE_CKPT_CONFIG: True