BASE_TASK_CONFIG_PATH: "configs/audionav/av_nav/replica/audiogoal_train_multiple.yaml"
SENSORS: ["DEPTH_SENSOR"]
NUM_UPDATES: 40000
LOG_INTERVAL: 10
CHECKPOINT_INTERVAL: 100 # 50
VIDEO_OPTION: []
VISUALIZATION_OPTION: []
MOVING: True
ENV_NAME: "SA2AudioNavRLEnv"
TRAINER_NAME: "SA2AVNavTrainer"
NUM_PROCESSES: 5
feature_type: 0
TORCH_GPU_ID: 0
SIMULATOR_GPU_ID: 0

batch_size_pre: 512
pre_model: "//data/AudioVisual/pre_train"
num_epoch: 20000
SOURCE_SOUND_IDS_PATH: "data/sounds/sound_ids_1s_all_not_merge_train.npy"
RL:
  PPO:
    # ppo params
    clip_param: 0.1
    ppo_epoch: 4
    num_mini_batch: 1
    value_loss_coef: 0.5
    entropy_coef: 0.20
    lr: 2.5e-4
    eps: 1e-5
    max_grad_norm: 0.5
    # decide the length of history that ppo encodes
    num_steps: 150
    hidden_size: 512
    use_gae: True
    gamma: 0.99
    tau: 0.95
    use_linear_clip_decay: True
    use_linear_lr_decay: True
    # window size for calculating the past rewards
    reward_window_size: 50

    is_visual_encode: False # if encode visual image to feature to the pipeline
    is_classify: False
    is_visual_classify: False
    is_regression: False
    is_against: True
    is_help_classify: False
    lambda_regressor: 0.0
    lambda_classifier: 0.0
    lambda_classifier_entropy: 0.0
    not_against_step_list: []
    is_reshape_groundtruth_loss: False
    use_buffer_train: False
    use_buffer_more: False
    buffer_maxlen: 10000
    train_batch: 512
    classifier_num_layers: 4
    load_ckpt: 0
    reg_behind: True
    classifier_behind: False
    double_ear: False
    classifier_lr: 2.5e-4
    normalize_config: "none"
    lambda_p_method: "sigmoid"

    is_confidence: False
AUDIO_NOISE_LEVEL: 0.033
DISTRACTOR_SOUND_DIR: data/sounds/1s_all_distractor/train
HAS_DISTRACTOR_SOUND: True
