BASE_TASK_CONFIG_PATH: "configs/audionav/av_wan/mp3d/audiogoal_without_gm.yaml"
NUM_PROCESSES: 1
SENSORS: ["DEPTH_SENSOR"]
TEST_EPISODE_COUNT: 1000
#VIDEO_OPTION: ["tensorboard"]
VIDEO_OPTION: []
VISUALIZATION_OPTION: []
ENCODE_DEPTH: False
USE_SYNC_VECENV: False


EVAL:
  SPLIT: "test_telephone"
  USE_CKPT_CONFIG: True