BASE_TASK_CONFIG_PATH: "configs/audionav/av_wan/mp3d/audiogoal_without_am.yaml"
NUM_PROCESSES: 5
SENSORS: ["DEPTH_SENSOR"]
NUM_UPDATES: 10000
LOG_INTERVAL: 10
CHECKPOINT_INTERVAL: 50
VIDEO_OPTION: []
VISUALIZATION_OPTION: []
ENCODE_DEPTH: False


RL:
  SUCCESS_REWARD: 10.0
  SLACK_REWARD: -0.01
  WITH_TIME_PENALTY: True
  WITH_DISTANCE_REWARD: True
  DISTANCE_REWARD_SCALE: 0.25
  WITH_PREDICTION_REWARD: False
  GOAL_PREDICTION_SCALE: 1.0

  PPO:
    # ppo params
    clip_param: 0.1
    ppo_epoch: 4
    num_mini_batch: 1
    value_loss_coef: 0.5
    entropy_coef: 0.02
    lr: 2.5e-4
    eps: 1e-5
    max_grad_norm: 0.5
    # decide the length of history that ppo encodes
    num_steps: 150
    hidden_size: 512
    use_gae: True
    gamma: 0.99
    tau: 0.95
    use_linear_clip_decay: True
    use_linear_lr_decay: True
    use_exponential_lr_decay: False
    exp_decay_lambda: 5.0
    # window size for calculating the past rewards
    reward_window_size: 50