ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
SIMULATOR:
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 1
  RGB_SENSOR:
    WIDTH: 128
    HEIGHT: 128
    HFOV: 130
  DEPTH_SENSOR:
    WIDTH: 128
    HEIGHT: 128
    HFOV: 130
    NORMALIZE_DEPTH: False
#    NOISE_MODEL: RedwoodDepthNoiseModel

  TYPE: "SoundSpacesSim"
  ACTION_SPACE_CONFIG: "v0"
  SCENE_DATASET: "mp3d"
  AUDIO:
    RIR_SAMPLING_RATE: 44100
    SOURCE_SOUND_IDS_PATH: "data/sounds/sound_ids_1s_all_not_merge.npy"

TASK:
  TYPE: AudioNav
  SUCCESS_DISTANCE: 0.2

  SENSORS: ['SPECTROGRAM_SENSOR']
  GOAL_SENSOR_UUID: spectrogram

  MEASUREMENTS: [ 'DISTANCE_TO_GOAL', 'NORMALIZED_DISTANCE_TO_GOAL', 'SUCCESS', 'SPL', 'SOFT_SPL', 'NUM_ACTION', 'SUCCESS_WEIGHTED_BY_NUM_ACTION']
  SPL:
    TYPE: SPL
    SUCCESS_DISTANCE: 0.2
    TOP_DOWN_MAP:
      MAP_RESOLUTION: 10000
      DRAW_SOURCE_AND_TARGET: True
      DRAW_BORDER: True
      DRAW_SHORTEST_PATH: False

DATASET:
  TYPE: "AudioNav"
  SPLIT: "test_multiple_unheard"
  CONTENT_SCENES: ["*"]
  VERSION: 'v1'
  SCENES_DIR: "data/scene_datasets/mp3d"
  DATA_PATH: "data/datasets/audionav/mp3d/{version}/{split}/{split}.json.gz"
